/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import CharacterInput from 'react-native-character-input';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

export default class App extends Component {
  state = {
    value: ''
  };

  render() {
    return (
      <View style={styles.container}>
        <CharacterInput
          placeHolder='YYYY/MM/DD'
          showCharBinary='1111011011'
          handleChange={(value) => this.setState({value})}
          inputType='underlined'
          keyboardType='numeric'
          autoFocus={true}
        />
        <CharacterInput
          placeHolder='YYYY/MM/DD'
          showCharBinary='1111011011'
          handleChange={(value) => this.setState({value})}
          inputType='outlined'
          keyboardType='numeric'
        />
        <CharacterInput
          placeHolder='YYYY/MM/DD'
          showCharBinary='1111011011'
          handleChange={(value) => this.setState({value})}
          inputType='contained'
          keyboardType='numeric'
        />
      </View>
    );
  };
};
